### ISSUE TITLE
如何测试

### ISSUE THREAD

**Issue by hfyer** [Zvenger/NAIC2020_ReID_R1#1]
大佬训练的时候可以自己测试结果吗，非得提交才能看到分数吗

**Comment by Zvenger** [comment]
我这个没有设置验证集，只能最后生成json文件，提交json在线看到分数。
想测试的话，可以从训练集中，自己分一些出来，做验证集。

但是，我之前比赛的时候，分出来的验证集，和线上测试没法正相关。有时候线下涨了，线上还会降。后来受限于计算资源，来不及重新划分验证集了，就没弄验证集了。
